plugins:
  - jekyll-remote-theme
remote_theme: apehex/jekyll-theme-consulting
title: Thuned LLC
description: Security consulting and paid speaking engagements
show_excerpts: true
exclude:
  - CLAUDE.md
  - README.md
